name: Compile and release for Windows, Linux and macOS

on:
  workflow_dispatch:

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  release:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: Get compilation artifacts
      uses: actions/download-artifact@v4

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: Executables
        tag_name: v1.0.0
        files: |
          ${{ needs.compile.outputs.project-name }}-windows-latest
          ${{ needs.compile.outputs.project-name }}-ubuntu-latest
          ${{ needs.compile.outputs.project-name }}-macos-latest
        make_latest: true
