name: Manual testing procedure
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: true

    steps:
    - name: Get repository files
      uses: actions/checkout@v4

    - name: View currend directory
      id: pwd
      shell: bash
      run: pwd
    
    - name: Set project name as reusable string
      id: strings
      shell: bash
      run: |
        echo "project-name=`echo '${{ github.workspace }}/src/CMakeLists.txt' | perl -pe 's!\\!\/!g' | cat | grep 'project(' | perl -pe 's/.*\((.*?)\s.*/$1/'`" >> "$GITHUB_OUTPUT"

    - name: Print project name
      run: echo ${{ steps.strings.outputs.project-name }}
