name: Variable custom file for testing commands on GitHub runners

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Show /bin to see what commands are installed
      run: ls /bin
      
